sample/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




 
Route::post('/product','ProductController@store');



Route::get('/validate','ProductController@store');

Route::get('/middle1','ProductController@samp')->middleware('samp:middleware demo');

Route::resource('student','studentcontroller');
Route::get('/show','studentcontroller@index');
//Route::get('/student','studentcontroller@store')->middleware('validate');


Route::get('/facadeex', function() {
    return TestFacades::testingFacades();
 });

 Route::group(['middleware'=>['Groups']],function(){
    Route::get('/', function () {
        return view('welcome');
    });
    Route::get('/product','ProductController@index');    
     
 });


Route::resource('Persons','PersonController');
Route::get('/retrieve','PersonController@index');

Route::resource('Querysamp','queryController');
Route::get('/email_validate','queryController@email_validate');

Route::resource('course','Coursecontroller');

Route::resource('country','Countrycontroller');

sample/resources/views/create.blade.php
<!DOCTYPE html>
<html>
    <body>
        <form method="POST" action="{{ route('student.store')}}">
            <label>Name:</label>
            <input type="text" name="name"/><br><br>
            
            <label>Mark 1:</label>
            <input type="text" name="mark1"/><br><br>
            
            <label>Mark 2:</label>
            <input type="text" name="mark2"/><br><br>
            
            <label>Mark 3:</label>
            <input type="text" name="mark3"/><br><br>

            <input type="submit" value="Submit"/>
        </form>
    </body>
</html>



<ul>
    @foreach($errors->all() as $error)
        <li>{{ $error }}</li>
    @endforeach
</ul>

sample/resources/views/createpers.blade.php
<html>

<body>
<form method="POST" action="{{ config('app.url')}}/person">
<label> Name:</label>
<input type="text" name="name"/><br><br>
<label>Age: </label>
<input type="number" name="age"/><br><br>

<input type="submit" value="Submit"/>
</form>
</body>
</html>

sample/resources/views/index.blade.php
<html>
    <body>
        <table border="1px">
            <thead>
                <tr>
                    <td>ID</td>
                    <td>Name</td>
                    <td>Mark 1</td>
                    <td>Mark 2</td>
                    <td>Mark 3</td>
                </tr>
            </thead>
            <tbody>
                @foreach($cruds as $crud)
                <tr>
                    <td>{{$crud->id}}</td>
                    <td>{{$crud->name}}</td>
                    <td>{{$crud->mark1}}</td>
                    <td>{{$crud->mark2}}</td>
                    <td>{{$crud->mark3}}</td>
                    <td>{{$crud->course}}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </body>
</html>

sample/resources/views/products.blade.php
<html>
    <body>
        <h1>Products Details</h1>
        <p>Name: Notebook</p>
        <form method='post'>
            @csrf
            <label>Name: </label>
            <input type="text" id="name"/><br><br>
            <label>Age: </label>
            <input type="number" id="age"/><br><br>
            <input type="submit" value="Submit"/>
</body>
</html>

<ul>
    @foreach($errors->all() as $error)
        <li>{{ $error }}</li>
    @endforeach
</ul>

sample/resources/views/show.blade.php
<html>
    <body>
        <table border="1">
            <tbody>
                @foreach($cruds as $crud)
                <tr>
                    <td>$crud->course->id</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </body>
</html>

sample/resources/views/validate.blade.php
<html>
    <body>
    <form method="post" action="/validate">
        <label>Username</label>
        <input type="text" name="name"/><br><br>
        <label>Password</label>
        <input type="password" name="pass"/><br><br>
        <input type="submit" value="Submit"/>
    </form>
</body>
</html>

<ul>
    @foreach($errors->all() as $error)
        <li>{{ $error }}</li>
    @endforeach
</ul>