sample/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




 
Route::post('/product','ProductController@store');



Route::get('/validate','ProductController@store');

Route::get('/middle1','ProductController@samp')->middleware('samp:middleware demo');

Route::resource('student','studentcontroller');
Route::get('/show','studentcontroller@index');
//Route::get('/student','studentcontroller@store')->middleware('validate');


Route::get('/facadeex', function() {
    return TestFacades::testingFacades();
 });

 Route::group(['middleware'=>['Groups']],function(){
    Route::get('/', function () {
        return view('welcome');
    });
    Route::get('/product','ProductController@index');    
     
 });


Route::resource('Persons','PersonController');
Route::get('/retrieve','PersonController@index');

Route::resource('Querysamp','queryController');
Route::get('/email_validate','queryController@email_validate');

Route::resource('course','Coursecontroller');

Route::resource('country','Countrycontroller');

sample/resources/views/QuerySample/create.blade.php
<!DOCTYPE html>
<html>
    <head>
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.min.js"></script>
        <script type="text/javascript" src="{{asset('validation/valid.js')}}"></script>
        <script type="text/javascript" src="{{asset('validation/addCss.js')}}"></script>
   </head>
    <body>
        
        <form method="POST" id="queryform" action="{{ route('Querysamp.store')}}">
            <label>Name:</label>
            <input type="text" name="name"/><br><br>

            
            <label>E-Mail: </label>
            <input type="text" name="email" class="keyup-email" value=""/><br><br>

            <label>Dropdown</label>
            <select name="dd" id="dd">
            </select>
            
            <input type="submit" value="Submit" id="button"/>
        </form>
    </body>
</html>

sample/resources/views/QuerySample/index.blade.php
<html>
    <body>
        <table border="1px">
            <thead>
                <tr>
                    <td>ID</td>
                    <td>Name</td>
                    <td>E-Mail</td>
                </tr>
            </thead>
            <tbody>
                @foreach($query as $data)
                <tr>
                    <td>{{$data->id}}</td>
                    <td>{{$data->name}}</td>
                    <td>{{$data->email}}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </body>
</html>