sample/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




 
Route::post('/product','ProductController@store');



Route::get('/validate','ProductController@store');

Route::get('/middle1','ProductController@samp')->middleware('samp:middleware demo');

Route::resource('student','studentcontroller');
Route::get('/show','studentcontroller@index');
//Route::get('/student','studentcontroller@store')->middleware('validate');


Route::get('/facadeex', function() {
    return TestFacades::testingFacades();
 });

 Route::group(['middleware'=>['Groups']],function(){
    Route::get('/', function () {
        return view('welcome');
    });
    Route::get('/product','ProductController@index');    
     
 });


Route::resource('Persons','PersonController');
Route::get('/retrieve','PersonController@index');

Route::resource('Querysamp','queryController');
Route::get('/email_validate','queryController@email_validate');

Route::resource('course','Coursecontroller');

Route::resource('country','Countrycontroller');

sample/app/Person.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Person extends Model
{
    protected $table='Persons';
    protected $fillable=['FirstName','LastName','mail','img'];
}

sample/app/Http/Controllers/PersonController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Person;
use App\Http\Requests\StorePerson;
use App\Http\Requests\UpdatePerson;
class PersonController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
        $persons=\App\Person::all();
        return view('Persons.index',compact('persons'));
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Persons.Create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StorePerson $request)
    {
        
        $person=new Person();
         
        $person->FirstName=$request->FirstName;
        $person->LastName=$request->LastName;
        $person->mail=$request->mail;
        if($files=$request->file('img')){  
            $name=$files->getClientOriginalName();  
            $files->move('laravelpictures',$name);  
            $person->img=$name;  
            }  
        $person->save();
        return redirect('/Persons')->with('success','Record Created Successfully');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $persons=\App\Person::findorFail($id);
        return view('Persons.edit', compact('persons'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([ 'FirstName'=>'required|alpha',
        'LastName'=>'required|alpha',
        'mail'=>'required|regex:/^(\w{2,})+@[a-zA-z]+\.[a-z]{2,3}$/|unique:persons,mail,'.$id,
        'img'=>'required|image|mimes:jpg,jpeg'        
    ]);

        
        $persons=Person::find($id);
        $persons->FirstName=$request->FirstName;
        $persons->LastName=$request->LastName;
        $persons->mail=$request->mail;
        if($files=$request->file('img')){  
            $name=$files->getClientOriginalName();  
            $files->move('laravelpictures',$name);  
            $persons->img=$name;  
            }  
        
        $persons->save();
        return redirect('/Persons')->with('success','Record Updated Successfully');
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $person=\App\Person::find($id);
        $person->delete();
        return redirect('/Persons')->with('success','Record Deleted Successfully');
    }
}

sample/resources/views/Persons/Create.blade.php
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="{{asset('design.css')}}">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    </head>
    <body>
        
        <p class="list"><button type="submit" class="btn btn-light"><a href="/Persons">Person's List</a></button></p>
        <div class="container1">
        <div class="cont">   
        <h4>Create Person</h4>
        <p id="req"><span>*</span>-Required</p></div>
        <table class="table1">
            <form method="POST" action="{{ route('Persons.store')}}" enctype="multipart/form-data">
            <tr>
                <td align="left">
                     <ul>
                     @foreach($errors->all() as $error)
                     <li class="error">{{ $error }}</li>
                     @endforeach
                    </ul>
                </td>
            </tr>
                <tr>
                    <td align="right"><label><span>*</span>First Name: </label></td>
                    <td align="left"><input type="text" name="FirstName" value="{{old('FirstName')}}"/></td>
                </tr>
                <tr>
                    <td align="right"><label><span>*</span>Last Name: </label></td>
                    <td align="left"><input type="text" name="LastName" value="{{old('LastName')}}"/></td>
                </tr>
                <tr>
                    <td align="right"><label><span>*</span>E-mail: </label></td>
                    <td align="left"><input type="text" name="mail" value="{{old('mail')}}"/></td>
                </tr>
                <tr>
                    <td align="right"><label><span>*</span>Choose a Image: </label></td>
                    <td align="left"><input type="file" name="img" value="{{old('img')}}"/></td>
                </tr>
                    <td></td><td align="left"><input type="Submit" class="btn btn-success" value="Save"/></td>
            </form>
        </table>
</div>

    </body>
</html>

sample/resources/views/Persons/edit.blade.php
<html>
    <head>
        <link rel="stylesheet" href="{{asset('design.css')}}">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    </head>
    
    <body>
        <br><br>
    <div class="container1">
        <h4>Edit a Record</h4>
        <form method="POST" action="{{ route('Persons.update',$persons->id)}}" enctype="multipart/form-data">

@method('PUT')

@csrf
            <table class="table1">
            <tr>
                <td align="left">
                     <ul>
                     @foreach($errors->all() as $error)
                     <li class="error">{{ $error }}</li>
                     @endforeach
                    </ul>
                </td>
            </tr>
            
                <tr>
                    <td align="right"><label>First Name: </label></td>
                    <td align="left"><input type="text" name="FirstName" value="{{$persons->FirstName}}"/></td>
                </tr>
                <tr>
                    <td align="right"><label>Last Name: </label></td>
                    <td align="left"><input type="text" name="LastName" value="{{$persons->LastName}}"/></td>
                </tr>
                <tr>
                    <td align="right"><label>E-mail: </label></td>
                    <td align="left"><input type="text" name="mail" value="{{$persons->mail}}"/></td>
                </tr>
                <tr>
                    <td align="right"><label>Choose a Image: </label></td>
                    <td align="left"><input type="file" name="img" value="{{$persons->img}}"/></td>
                </tr>
                    <td></td><td align="left"><input type="Submit" class="btn btn-success" value="Save"/></td>
            
            </table>
        </form>
    </div>
</body>
</html>

sample/resources/views/Persons/index.blade.php
<html>
    <head>
    <link rel="stylesheet" href="{{asset('design.css')}}">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    </head>
    <body>
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{$message}}</p>
        </div>
    @endif
    <br>
    <p class="list"><button type="submit" class="btn btn-light"><a href="/Persons/create">Add New Person</a></button></p>

        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>FirstName</th>
                    <th>LastName</th>
                    <th>Email</th>
                    <th>Image</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                @foreach($persons as $person)
                <tr>
                    <td>{{$person->id}}</td>
                    <td>{{$person->FirstName}}</td>
                    <td>{{$person->LastName}}</td>
                    <td>{{$person->mail}}</td>
        
                    <td><img src="./laravelpictures/{{$person->img}}" height="40" width="40"/></td>
                    <td>
                        <form action="{{ route('Persons.edit',$person->id)}}">
                        <button type="submit">Edit</button></a>
                        </form>
                    </td>
                    <td>
                        <form action="{{ route('Persons.destroy',$person->id)}}" method="POST">
                        @method('DELETE')
                        @csrf
                        <button type="submit">Delete</button>
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </body>
</html>