sample/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




 
Route::post('/product','ProductController@store');



Route::get('/validate','ProductController@store');

Route::get('/middle1','ProductController@samp')->middleware('samp:middleware demo');

Route::resource('student','studentcontroller');
Route::get('/show','studentcontroller@index');
//Route::get('/student','studentcontroller@store')->middleware('validate');


Route::get('/facadeex', function() {
    return TestFacades::testingFacades();
 });

 Route::group(['middleware'=>['Groups']],function(){
    Route::get('/', function () {
        return view('welcome');
    });
    Route::get('/product','ProductController@index');    
     
 });


Route::resource('Persons','PersonController');
Route::get('/retrieve','PersonController@index');

Route::resource('Querysamp','queryController');
Route::get('/email_validate','queryController@email_validate');

Route::resource('course','Coursecontroller');

Route::resource('country','Countrycontroller');

sample/app/Country.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Country extends Model
{
    protected $table="countries";
    protected $fillable=['name','countrystuc_id','countrystuc_type'];

    public function countrystuc(){
        return $this->morphTo();
    }
}

sample/app/Http/Controllers/Countrycontroller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Country;
class Countrycontroller extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('countries.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'=>'required|alpha',
            'countrystuc_id'=>'required|Integer',
            'countrystuc_type'=>'required'
        ]);
            $country=new Country();
            $country->name=$request->name;
            $country->countrystuc_id=$request->countrystuc_id;
            $country->countrystuc_type=$request->countrystuc_type;
            $country->save();
            return redirect('/country');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

sample/resources/views/countries/create.blade.php
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="{{asset('design.css')}}">
    </head>
    <body>
        <form action="{{ route('country.store')}}" method="POST">
            <table>
                <tr>
                    <td align="right"><label>Country name:</label></td>
                    <td align="left"><input type="text" name="name"/>
                </tr>
                <tr>
                    <td align="right"><label>Countrystuc_id:</label></td>
                    <td align="left"><input type="text" name="countrystuc_id"/>
                </tr>
                <tr>
                    <td align="right"><label>Countrystuc_type:</label></td>
                    <td align="left"><input type="text" name="countrystuc_type"/>
                </tr>
                <tr>
                    <td></td>
                    <td><input type="submit" value="Submit"/></td>
                </tr>
         
            </table>
        </form>
    </body>
</html>



<ul>
    @foreach($errors->all() as $error)
    <li class="error">{{ $error }}</li>
    @endforeach
</ul>